### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by uriva** [m-bain/whisperX#513] opened 2023-10-07 22:38 UTC
```
Exception in thread Transcriber Function:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/uri/uriva/whisperx-server/whisperx/worker.py", line 38, in work
    self.work_on_file(model, audio_path, output_dir, task)
  File "/home/uri/uriva/whisperx-server/whisperx/worker.py", line 61, in work_on_file
    result_aligned = align(
                     ^^^^^^
  File "/home/uri/uriva/whisperx-server/whisperx/alignment.py", line 302, in align
    char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pandas/core/frame.py", line 6209, in reset_index
    new_obj.insert(
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4772, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert subsegment-idx, already exists
```

**Comment by projects-g** [comment] 2023-10-09 09:56
Faced this today:

`Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 352, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 438, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/diarize.py", line 469, in transcribe_segment
    result_aligned = whisperx.align(
  File "/usr/local/lib/python3.10/site-packages/whisperx/alignment.py", line 302, in align
    char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 6223, in reset_index
    new_obj.insert(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4934, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert subsegment-idx, already exists`

**Comment by Barabazs** [comment] 2024-12-16 09:37
Duplicate of #176

**Closed by Barabazs** 2024-12-16 09:37 UTC
