### ISSUE TITLE
ValueError: cannot insert subsegment-idx, already exists

### ISSUE THREAD

**Issue by PabloSergi** [m-bain/whisperX#239] opened 2023-05-10 10:22 UTC
Hi, caught this error today. A little background, I have an audio recording, I cut it into many small pieces, then I transcribe them. Here with one of the short pieces occurs this error. I didn't make any adjustments to whisperx code, but I work with it through flask server.

[2023-05-10 10:06:20,551: WARNING/ForkPoolWorker-1] Finished transcribing audio using Whisper.
[2023-05-10 10:06:20,551: WARNING/ForkPoolWorker-1] Loading alignment model...
1.20.173.56 - - [10/May/2023 10:06:20] "GET /task_status/88fb8fae-346f-4fcd-bef7-0d45054891de HTTP/1.1" 200 -
[2023-05-10 10:06:22,781: WARNING/ForkPoolWorker-1] Alignment model loaded.
[2023-05-10 10:06:22,781: WARNING/ForkPoolWorker-1] Aligning Whisper output...
[2023-05-10 10:06:23,618: ERROR/ForkPoolWorker-1] Task app.transcribe_audio_task[88fb8fae-346f-4fcd-bef7-0d45054891de] raised unexpected: ValueError('cannot insert subsegment-idx, already exists')
Traceback (most recent call last):
  File "/home/pablo_sergi/anaconda3/envs/test/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/pablo_sergi/anaconda3/envs/test/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/pablo_sergi/testproj/whisperx/app.py", line 35, in transcribe_audio_task
    result_aligned = whisperx.align(result["segments"], model_a, metadata, audio_path, device="cpu")
  File "/home/pablo_sergi/testproj/whisperx/whisperx/alignment.py", line 301, in align
    char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
  File "/home/pablo_sergi/anaconda3/envs/test/lib/python3.8/site-packages/pandas/core/frame.py", line 6219, in reset_index
    new_obj.insert(
  File "/home/pablo_sergi/anaconda3/envs/test/lib/python3.8/site-packages/pandas/core/frame.py", line 4782, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert subsegment-idx, already exists
1.20.173.56 - - [10/May/2023 10:06:26] "GET /task_status/88fb8fae-346f-4fcd-bef7-0d45054891de HTTP/1.1" 200 -

**Comment by Barabazs** [comment] 2024-12-16 09:37
Duplicate of #176

**Closed by Barabazs** 2024-12-16 09:37 UTC
