### ISSUE TITLE
Enhancement: Produce interview transcript output

### ISSUE THREAD

**Issue by eplinux** [m-bain/whisperX#138] opened 2023-03-16 17:57 UTC
Dear all,

all in all this script works pretty decent so far, thank you very much. However, I noticed that only the .ass output still contains the info on who speaks gained from diarization. As my use case is transcribing qualitative interviews, I'm obviously interested in retaining this information so I have an interview transcript containing speakers and timestamps as an output. Maybe there is even a way to convert ass files into such a format but I haven't been lucky with finding it yet.

Therefore, I would suggest this as a feature request because I think it'd benefit a lot of people while being somewhat easy to implement?

Best

**Comment by kangagoo** [comment] 2023-03-16 19:17
I think this is a duplicate of #137, which I'm the author of, and I did not get any replies. Maybe I was just too lengthy ;-).

After not getting replies, I just asked GPT-4 to write a script using the SRT file as input and a sample output on how I wanted it to look like. The SRT file contains all the necessary information and is more straightforward to process than the ASS file.

In Python (you can test it [here](https://replit.com/languages/python3)):

```
import re

def parse_srt(input):
    entries = input.strip().split("\n\n")
    output_lines = []
    last_speaker = None
    
    for entry in entries:
        lines = entry.strip().split("\n")
        time_start = lines[1].split(" --> ")[0]
        speaker, text = re.match(r'\[(.+)\]:\s*(.+)', lines[2]).groups()
        
        if last_speaker and speaker != last_speaker:
            output_lines.append("")
        
        if output_lines and speaker == last_speaker:
            output_lines[-1] += " " + text
        else:
            output_lines.append(f"[{speaker}, {time_start}] {text}")
        
        last_speaker = speaker

    return "\n".join(output_lines)

input_text = """
1
00:00:00,040 --> 00:00:00,240
[SPEAKER_02]: Good

2
00:00:01,761 --> 00:00:01,941
[SPEAKER_02]: morning

3
00:00:01,981 --> 00:00:02,141
[SPEAKER_02]: everybody!

4
00:00:02,181 --> 00:00:02,321
[SPEAKER_00]: Morning

5
00:00:02,361 --> 00:00:02,621
[SPEAKER_00]: Frank

6
00:00:03,261 --> 00:00:03,481
[SPEAKER_01]: Hiya

7
00:00:03,501 --> 00:00:03,721
[SPEAKER_01]: all

8
00:00:06,463 --> 00:00:06,523
[SPEAKER_01]: of 

9
00:00:06,603 --> 00:00:06,823
[SPEAKER_01]: you

10
00:00:06,883 --> 00:00:07,183
[SPEAKER_00]: Whats

11
00:00:08,603 --> 00:00:08,763
[SPEAKER_00]: up,

12
00:00:08,803 --> 00:00:08,964
[SPEAKER_00]: Michael?

13
00:00:08,803 --> 00:00:08,964
[SPEAKER_02]: Let's rock!
"""

output = parse_srt(input_text)
print(output)


```

Output:

[SPEAKER_02, 00:00:00,040] Good morning everybody!

[SPEAKER_00, 00:00:02,181] Morning Frank

[SPEAKER_01, 00:00:03,261] Hiya all of you

[SPEAKER_00, 00:00:06,883] Whats up, Michael?

[SPEAKER_02, 00:00:08,803] Let's rock!

If you prefer another language, let GPT-4 know - it works quite well.

**Comment by eplinux** [comment] 2023-03-16 19:30
Thank so much! Why didn't I think about that? 

Out of curiosity, could you also tell it to write a script that reads the SRT input file and writes the output to a new srt file? I don't have a premium subscription so I can only try the older one.

**Comment by eplinux** [comment] 2023-03-16 20:25
Okay, it took me quite a while to come up with a working script but this seems to work pretty well now:

```
import sys

# read in source file from argument
filename = sys.argv[1]
with open(filename, 'r') as f:
    lines = f.readlines()

# merge subsequent lines with same speaker ID
new_lines = []
current_speaker = ''
current_text = ''
current_start_time = ''
current_end_time = ''
count = 1
for line in lines:
    if '-->' in line:
        current_start_time, current_end_time = line.strip().split(' --> ')
    elif line.startswith('['):
        speaker_id, text = line.strip().split(']: ')
        if speaker_id == current_speaker:
            current_text += ' ' + text
            count += 1
        else:
            if current_speaker:
                new_lines.append(str(count) + '\n')
                new_lines.append(current_start_time + ' --> ' + current_end_time + '\n')
                new_lines.append('[' + current_speaker + ']: ' + current_text.strip() + '\n\n')
            current_speaker = speaker_id
            current_text = text
            current_start_time = ''
            current_end_time = ''
            count = 1

# add last speaker's lines to new_lines
new_lines.append(str(count) + '\n')
new_lines.append(current_start_time + ' --> ' + current_end_time + '\n')
new_lines.append('[' + current_speaker + ']: ' + current_text.strip() + '\n\n')

# write output to new file
new_filename = filename.split('.')[0] + '_modified.srt'
with open(new_filename, 'w') as f:
    f.writelines(new_lines)
    
print(f'Successfully modified {filename} and saved as {new_filename}')

```

which can be executed like this: 

`python merge_srt_lines.py source_file.srt`

Since it's ai generated, try at your own risk, everybody :)

**Closed** 2023-04-01 13:40 UTC
