### ISSUE TITLE
Torch: Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by akparhi** [m-bain/whisperX#14] opened 2022-12-25 09:08 UTC
For a longer file on M1 Pro, I keep getting this error after about 22min of alignment: 
![Screen Shot 2022-12-25 at 2 35 21 PM](https://user-images.githubusercontent.com/22069968/209462467-93f86ad2-450f-4684-bfe3-25f6248f8343.png)

Reproduction repo: https://github.com/akparhi/pyvtt/tree/dev
Request with 1hr youtube video: `curl --location --request POST 'http://localhost:8000/speech-to-text' \
--header 'Content-Type: application/json' \
--data-raw '{
    "url": "https://www.youtube.com/watch?v=MYrfLmm_cT4",
    "accuracy": "word",
}'`

**Comment by mu4farooqi** [comment] 2022-12-29 07:03
I also faced similar bug. It's probably caused by Whisper hallucinations i.e. whisper gives very weird sentences at the end which are not part of original transcript.

**Comment by m-bain** [comment] 2022-12-29 10:54
ah yes, that makes sense, thanks @mu4farooqi 
Fixed in https://github.com/m-bain/whisperX/commit/93d661f2e4b416770052c28e99a4f2d583259686

**Comment by akparhi** [comment] 2022-12-29 22:42
@m-bain even with the latest commit, the error is reproducible with the same video transcribing and alligning. 
![image](https://user-images.githubusercontent.com/22069968/210017998-02f3c4df-85f9-4f23-8bc5-d5ec09bf8b42.png)

**Comment by akparhi** [comment] 2022-12-29 22:53
Both times it failed at exactly after aligning till 23:58
![image](https://user-images.githubusercontent.com/22069968/210018677-d6c08ef0-2605-41bc-8089-7173ba31660a.png)

**Comment by mu4farooqi** [comment] 2022-12-30 00:43
I haven’t gone through the implementation of this library yet. But the fix for this bug is just stripping any segment after audio end time.

Unfortunately Whisper’s hallucinations don’t exceed the audio end time. I remember getting a transcript with 2670s long audio file. In the transcript, last correct line had a timestamp of 2648s and remaining were hallucinations.

**Comment by m-bain** [comment] 2022-12-30 10:24
@akparhi can you share the whisper output before alignment? It seems the segment timestamps being inputted to the alignment model is of duration 0 and curious how this is happening

**Comment by akparhi** [comment] 2022-12-30 13:50
It breaks here: 
![image](https://user-images.githubusercontent.com/22069968/210077153-5342f1ad-b2dd-47f9-bde0-6be1223fd02c.png)

**Comment by akparhi** [comment] 2022-12-30 13:52
My mistake, I think the next block is the one which breaks. As you can see start is after end.

![image](https://user-images.githubusercontent.com/22069968/210077279-2d3d9eff-2e14-428a-bb6c-8b6792ae423d.png)

**Comment by akparhi** [comment] 2022-12-30 19:05
Would filtering out segments where end is before start make sense?

**Comment by akparhi** [comment] 2022-12-30 21:28
For now I've filtered the segments with wrong timestamps and fixed this issue. But there's another issue I'm facing: 
![image](https://user-images.githubusercontent.com/22069968/210112871-ddccd1c7-4241-4ddf-a8ad-e013867389cf.png)

**Comment by antonmihaylov** [comment] 2023-01-04 18:26
I had the same problem and can confirm that removing segments where start is after end works. 

```
# Remove faulty segments
def is_segment_valid(segment):
    return segment["start"] < segment["end"]


result["segments"] = list(filter(is_segment_valid, result["segments"]))
```

**Comment by mu4farooqi** [comment] 2023-01-04 19:19
I'm also seeing `raise ValueError("Failed to align")`. This happens when a segment has hallucinations i.e. transcription generated by Whisper for a given segment has extra words at the end. This causes trellis matrix to have `inf` values which causes backtracking to fail.

**Comment by mu4farooqi** [comment] 2023-01-04 19:20
You can reproduce this error by simply taking a pseudo segment and add some random extra text at the end of it.

**Comment by m-bain** [comment] 2023-01-05 11:18
thanks for investigating, crazy whisper can output start time after end time :'), I guess this is risk with decoding timestamps like this / without grounding / training on noisy data.

I added fallback to original timestamp in for the case of failed alignments: https://github.com/m-bain/whisperX/commit/5a668a7d8078f5a0efa62f80869c64cf00d47cca

@mu4farooqi yes VAD will definitely help as you describe, I think it's extra important for non-english, however I am hesitant to add another model to the pipeline and add to the complexity/dependencies

**Closed** 2023-01-05 11:24 UTC
Labels: bug
