### ISSUE TITLE
conflict on soundfile version with pyannote

### ISSUE THREAD

**Issue by laphang** [m-bain/whisperX#116] opened 2023-03-05 00:37 UTC
Hi, the latest commit below causes a pip install conflict with pyannote due to soundfile requirements. 

It's quite useful to use both packages together, so it'd be good to maintain a way to be able to install both. 

```
2023-03-05T11:08:46.723+11:00   ERROR: Cannot install -r /opt/ml/model/code/requirements.txt (line 16) and -r /opt/ml/model/code/requirements.txt (line 19) because these package versions have conflicting dependencies.
2023-03-05T11:08:46.723+11:00   The conflict is caused by: pyannote-audio 2.1.1 depends on soundfile<0.11 and >=0.10.2 whisperx 1.0 depends on soundfile>=0.12.0
```

https://github.com/m-bain/whisperX/commit/844eb30710f3e5207e6b312251c3cb20d87c4017

**Comment by cnbeining** [comment] 2023-03-05 04:27
Sorry for missing your issue - I've proposed fixes and have reached out to upstream on this matter.

> Very short term: Install WhisperX, and force upgrade pyannote.audio with pip install pyannote.audio -U to bring pyannote.audio to version 2.1.1.

ref: #118

**Comment by laphang** [comment] 2023-03-05 05:18
No worries, thanks for the quick response. For now, I'm just pip installing whisperX to the commit before the change above, and it's working ok for now.

**Comment by Barabazs** [comment] 2024-12-16 08:29
Duplicate of #118

**Closed by Barabazs** 2024-12-16 08:29 UTC
